version: '3.8'
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=project
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    image: node:18.16.1
    command: [ 'tail', '-f', '/dev/null' ]
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
volumes:
  db:
    driver: local
 
